// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNE15FJBFReJdIEv7A96ypLBdJCvsX84g',
    appId: '1:13160125173:web:dcf78f27644d67e179abbc',
    messagingSenderId: '13160125173',
    projectId: 'chatty-app-9dbc1',
    authDomain: 'chatty-app-9dbc1.firebaseapp.com',
    storageBucket: 'chatty-app-9dbc1.appspot.com',
    measurementId: 'G-KG8WPMRFWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXdUe4b64vRt2Sv7zT8edToOwV22uMBM',
    appId: '1:13160125173:android:1cdedfe1b8a169b579abbc',
    messagingSenderId: '13160125173',
    projectId: 'chatty-app-9dbc1',
    storageBucket: 'chatty-app-9dbc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4Ae6QoDIqdbwgWX-ASaDHJsNjDD1tCs',
    appId: '1:13160125173:ios:fb37ccdc20530f5c79abbc',
    messagingSenderId: '13160125173',
    projectId: 'chatty-app-9dbc1',
    storageBucket: 'chatty-app-9dbc1.appspot.com',
    iosBundleId: 'com.example.chatlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK4Ae6QoDIqdbwgWX-ASaDHJsNjDD1tCs',
    appId: '1:13160125173:ios:b15f40ba92a99ca979abbc',
    messagingSenderId: '13160125173',
    projectId: 'chatty-app-9dbc1',
    storageBucket: 'chatty-app-9dbc1.appspot.com',
    iosBundleId: 'com.example.chatlyApp.RunnerTests',
  );
}
